name: Build and Publish Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: bhprashanth0@gmail.com
           password: Prashanth@123

      - name: Build Docker image
        run: docker build -t 9880135088/product_display_project:latest .

      - name: Push Docker image
        run: docker push 9880135088/product_display_project:latest
